name: Build main branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: released

env:
  VITE_COMMIT_HASH: ${{ github.sha }}

jobs:
  build:
    name: Build vue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: mymindstorm/setup-emsdk@v11

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        run: yarn

      - name: build project
        run: yarn build

      - name: Deploy to the PROD server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: '-avz'
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_PROD_PATH }}
      
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: prod_dist
          path: ./dist
          if-no-files-found: error